"""
generate_tween_types.py
─────────────────────────────────────────────────────────────────────────────
Generates one header per tween type into:
  Source/TypeTween/Public/Blueprints/Generated/

ADDING A NEW TYPE
  1. Add an entry to TWEEN_TYPES below.
  2. Run this script.
  3. Recompile the plugin.

MODIFYING THE TEMPLATE
  Edit TweenAsyncType.h.template (sits next to this script).
  Available variables:
    ${TYPE_NAME}    — e.g.  Float | Vector | Transform
    ${CPP_TYPE}     — e.g.  float | FVector | FTransform
    ${DEFAULT_FROM} — e.g.  " = 0.f"  (include leading space, or leave empty "")
    ${DEFAULT_TO}   — e.g.  " = 1.f"
    ${CATEGORY}     — e.g.  "Tweening|Float"
    ${DISPLAY_NAME} — e.g.  "Tween Float"
    ${TOOLTIP}      — tooltip shown in Blueprint

Generated by Claud.ai
"""

from __future__ import annotations
from pathlib import Path
from string import Template

# ─── Paths ────────────────────────────────────────────────────────────────────

SCRIPT_DIR   = Path(__file__).parent
REPO_ROOT    = SCRIPT_DIR.parent
TEMPLATE_FILE = SCRIPT_DIR / "TweenAsyncType.h.template"
OUTPUT_DIR   = REPO_ROOT / "Source" / "TypeTween" / "Public" / "Blueprints" / "Generated"

# ─── Type definitions ─────────────────────────────────────────────────────────
# Each dict maps 1-to-1 with the template variables listed above.
# DEFAULT_FROM / DEFAULT_TO: include " = " prefix, or use "" to leave the
# member default-initialised by UE (e.g. FTransform has a sensible default).

TWEEN_TYPES: list[dict[str, str]] = [
    {
        "TYPE_NAME":    "Float",
        "CPP_TYPE":     "float",
        "DEFAULT_FROM": " = 0.f",
        "DEFAULT_TO":   " = 1.f",
        "CATEGORY":     "TypeTween",
        "DISPLAY_NAME": "Tween Float",
        "TOOLTIP":      "Tweens a float from [From] to [To].",
    },
    {
        "TYPE_NAME":    "Double",
        "CPP_TYPE":     "double",
        "DEFAULT_FROM": " = 0.0",
        "DEFAULT_TO":   " = 1.0",
        "CATEGORY":     "TypeTween",
        "DISPLAY_NAME": "Tween Double",
        "TOOLTIP":      "Tweens a double from [From] to [To].",
    },
    {
        "TYPE_NAME":    "Vector",
        "CPP_TYPE":     "FVector",
        "DEFAULT_FROM": " = FVector::ZeroVector",
        "DEFAULT_TO":   " = FVector::OneVector",
        "CATEGORY":     "TypeTween",
        "DISPLAY_NAME": "Tween Vector",
        "TOOLTIP":      "Tweens an FVector from [From] to [To].",
    },
    {
        "TYPE_NAME":    "Vector2D",
        "CPP_TYPE":     "FVector2D",
        "DEFAULT_FROM": " = FVector2D::ZeroVector",
        "DEFAULT_TO":   " = FVector2D::UnitVector",
        "CATEGORY":     "TypeTween",
        "DISPLAY_NAME": "Tween Vector2D",
        "TOOLTIP":      "Tweens an FVector2D from [From] to [To].",
    },
    {
        "TYPE_NAME":    "Rotator",
        "CPP_TYPE":     "FRotator",
        "DEFAULT_FROM": " = FRotator::ZeroRotator",
        "DEFAULT_TO":   " = FRotator::ZeroRotator",
        "CATEGORY":     "TypeTween",
        "DISPLAY_NAME": "Tween Rotator",
        "TOOLTIP":      "Tweens an FRotator from [From] to [To].",
    },
    {
        "TYPE_NAME":    "LinearColor",
        "CPP_TYPE":     "FLinearColor",
        "DEFAULT_FROM": " = FLinearColor::Black",
        "DEFAULT_TO":   " = FLinearColor::White",
        "CATEGORY":     "TypeTween",
        "DISPLAY_NAME": "Tween Linear Color",
        "TOOLTIP":      "Tweens an FLinearColor from [From] to [To].",
    },
    {
        "TYPE_NAME":    "Transform",
        "CPP_TYPE":     "FTransform",
        "DEFAULT_FROM": "",   # FTransform default-constructs to identity — no initialiser needed
        "DEFAULT_TO":   "",
        "CATEGORY":     "TypeTween",
        "DISPLAY_NAME": "Tween Transform",
        "TOOLTIP":      "Tweens an FTransform from [From] to [To].",
    },
]

# ─── Generator ────────────────────────────────────────────────────────────────

def load_template() -> Template:
    if not TEMPLATE_FILE.exists():
        raise FileNotFoundError(
            f"Template not found: {TEMPLATE_FILE}\n"
            "Make sure TweenAsyncType.h.template is in the same folder as this script."
        )
    return Template(TEMPLATE_FILE.read_text(encoding="utf-8"))


def generate(tween_type: dict[str, str], template: Template) -> str:
    try:
        return template.substitute(tween_type)
    except KeyError as e:
        raise KeyError(
            f"Template variable {e} not found in type definition for "
            f"'{tween_type.get('TYPE_NAME', '?')}'. "
            f"Add it to the dict or remove it from the template."
        ) from e


def main() -> None:
    template = load_template()
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    generated: list[str] = []
    skipped:   list[str] = []

    for tween_type in TWEEN_TYPES:
        name        = tween_type["TYPE_NAME"]
        output_path = OUTPUT_DIR / f"TweenAsync{name}.h"
        content     = generate(tween_type, template)

        # Skip write if file is already up to date (avoids spurious UBT rebuilds)
        if output_path.exists() and output_path.read_text(encoding="utf-8") == content:
            skipped.append(name)
            continue

        output_path.write_text(content, encoding="utf-8")
        generated.append(name)

    # ── Summary ──
    print(f"Output directory: {OUTPUT_DIR.resolve()}")
    print()

    if generated:
        print(f"Generated ({len(generated)}):")
        for name in generated:
            print(f"  ✓  TweenAsync{name}.h")

    if skipped:
        print(f"\nAlready up to date ({len(skipped)}):")
        for name in skipped:
            print(f"  –  TweenAsync{name}.h")

    print(f"\nDone. {len(generated)} file(s) written, {len(skipped)} unchanged.")


if __name__ == "__main__":
    main()