#include "Blueprints/TweenNodeBase.h"

void UK2Node_Tween::AllocateDefaultPins() {
	Super::AllocateDefaultPins();

	// Mark the advanced output delegate pins that Super created.
	// The input sub-pins don't exist yet (splitting happens in
	// PostPlacedNewNode / PostReconstructNode), so they're handled there.
	for (const FName& Name : AdvancedDelegatePins())
		if (UEdGraphPin* P = FindPin(Name))
			P->bAdvancedView = true;

	AdvancedPinDisplay = ENodeAdvancedPins::Hidden;
}

void UK2Node_Tween::PostPlacedNewNode() {
	Super::PostPlacedNewNode();
	EnsureSplitState();
	EnsureAdvancedView();
	EnsureHiddenState();
}

void UK2Node_Tween::PostReconstructNode() {
	Super::PostReconstructNode();
	EnsureAdvancedView();
	EnsureHiddenState();
}

void UK2Node_Tween::GetMenuActions(FBlueprintActionDatabaseRegistrar& Reg) const {
	UClass* Cls = GetClass();
	/* Only register concrete subclasses, never the base itself */
	if (Cls == UK2Node_Tween::StaticClass()) { return; }
	if (Reg.IsOpenForRegistration(Cls))
		Reg.AddBlueprintAction(Cls, UBlueprintNodeSpawner::Create(Cls));
}

void UK2Node_Tween::PinDefaultValueChanged(UEdGraphPin* Pin) {
	Super::PinDefaultValueChanged(Pin);

	static const FName Names[] = {
		TEXT("Tween_Settings_Ease"),
		TEXT("Tween_Settings_RepeatCount"),
		TEXT("Tween_Settings_LoopMode"),
	};

	for (const FName& Name : Names) {
		if (Pin->PinName == Name) {
			EnsureHiddenState();
			if (UEdGraph* Graph = GetGraph()) {
				Graph->NotifyGraphChanged();
			}
		}
	}
}

void UK2Node_Tween::EnsureSplitState() {
	const UEdGraphSchema_K2* Schema = GetDefault<UEdGraphSchema_K2>();

	// Level 1: FTweenFloatConfig  From, To, Settings
	if (UEdGraphPin* P = FindPin(TEXT("Tween")))
		if (P->SubPins.Num() == 0)
			Schema->SplitPin(P);

	// Level 2: FTweenSettings  Duration, Ease, RepeatCount, LoopMode, Delays
	if (UEdGraphPin* P = FindPin(TEXT("Tween_Settings")))
		if (P->SubPins.Num() == 0)
			Schema->SplitPin(P);

	// Level 3: FTweenDelays Start, Reverse, Repeat, End
	// Pre-splitting here means individual float pins are already visible
	// when \/ is opened, rather than a blob the user would need to split.
	if (UEdGraphPin* P = FindPin(TEXT("Tween_Settings_Delays")))
		if (P->SubPins.Num() == 0)
			Schema->SplitPin(P);

	CustomizedSplits();
}

void UK2Node_Tween::EnsureHiddenState() {
	// when ease != CustomCurve:
	//		hide CustomEaseCurve
	const UEdGraphPin* EasePin = FindPin(TEXT("Tween_Settings_Ease"));
	if (EasePin) {
		const UEnum* EaseEnum = StaticEnum<ETweenEase>();
		if (EaseEnum) {
			const FString& EaseValue = EasePin->DefaultValue.IsEmpty()
				? EasePin->AutogeneratedDefaultValue
				: EasePin->DefaultValue;
			const int64 EnumValue = EaseEnum->GetValueByNameString(EaseValue);
			const ETweenEase CurrentEase = static_cast<ETweenEase>(EnumValue);

			// Hide CustomEaseCurve if Ease != CustomCurve
			if (UEdGraphPin* CustomEaseCurvePin = FindPin(TEXT("Tween_Settings_CustomEaseCurve"))) {
				CustomEaseCurvePin->bHidden = (CurrentEase != ETweenEase::CustomCurve);
			}
		}
	}

	// when repeat count != 0
	//		show dleays repeat 
	//		On Repeat
	const UEdGraphPin* RepeatCountPin = FindPin(TEXT("Tween_Settings_RepeatCount"));
	if (RepeatCountPin) {
		const FString& RepeatCountValue = RepeatCountPin->DefaultValue.IsEmpty()
			? RepeatCountPin->AutogeneratedDefaultValue
			: RepeatCountPin->DefaultValue;
		const int32 RepeatCount = FCString::Atoi(*RepeatCountValue);

		// Hide Delays.Repeat and OnRepeat if RepeatCount == 0
		if (UEdGraphPin* RepeatDelayPin = FindPin(TEXT("Tween_Settings_Delays_Repeat"))) {
			RepeatDelayPin->bHidden = (RepeatCount == 0);
		}
		if (UEdGraphPin* OnRepeatPin = FindPin(TEXT("OnRepeat"))) {
			OnRepeatPin->bHidden = (RepeatCount == 0);
		}
	}

	// when loop mode == ping pong:
	//		show Delays reverse 
	//		show On Reverse Begin
	const UEdGraphPin* LoopModePin = FindPin(TEXT("Tween_Settings_LoopMode"));
	if (LoopModePin) {
		const FString& LoopModeValue = LoopModePin->DefaultValue.IsEmpty()
			? LoopModePin->AutogeneratedDefaultValue
			: LoopModePin->DefaultValue;
		const int64 EnumValue = StaticEnum<ETweenLoopMode>()->GetValueByNameString(LoopModeValue);
		const ETweenLoopMode CurrentLoopMode = static_cast<ETweenLoopMode>(EnumValue);

		if (UEdGraphPin* ReverseDelayPin = FindPin(TEXT("Tween_Settings_Delays_Reverse"))) {
			ReverseDelayPin->bHidden = (CurrentLoopMode != ETweenLoopMode::PingPong);
		}
		if (UEdGraphPin* OnReverseBeginPin = FindPin(TEXT("OnReverseBegin"))) {
			OnReverseBeginPin->bHidden = (CurrentLoopMode != ETweenLoopMode::PingPong);
		}
	}
}

void UK2Node_Tween::EnsureAdvancedView() {
	/* Hide all Tween settings except Duration and Ease by default */
	for (UEdGraphPin* P : Pins) {
		const FString Name = P->PinName.ToString();

		if (!Name.StartsWith(TEXT("Tween_Settings"))) { continue; }
		if (Name == TEXT("Tween_Settings_Duration")) { continue; }
		if (Name == TEXT("Tween_Settings_Ease")) { continue; }
		if (Name == TEXT("Tween_Settings_CustomEaseCurve")) { continue; }

		P->bAdvancedView = true;
	}

	CustomizedAdvanced();
}
