#include "Blueprints/TweenNodeBase.h"

void UK2Node_Tween::AllocateDefaultPins() {
	Super::AllocateDefaultPins();

	// Mark the advanced output delegate pins that Super created.
	// The input sub-pins don't exist yet (splitting happens in
	// PostPlacedNewNode / PostReconstructNode), so they're handled there.
	for (const FName& Name : AdvancedDelegatePins())
		if (UEdGraphPin* P = FindPin(Name))
			P->bAdvancedView = true;

	AdvancedPinDisplay = ENodeAdvancedPins::Hidden;
}

void UK2Node_Tween::PostPlacedNewNode() {
	Super::PostPlacedNewNode();
	EnsureSplitState();
	EnsureAdvancedView();
	EnsureHiddenState();
}

void UK2Node_Tween::PostReconstructNode() {
	Super::PostReconstructNode();
	EnsureAdvancedView();
	EnsureHiddenState();
}

void UK2Node_Tween::GetMenuActions(FBlueprintActionDatabaseRegistrar& Reg) const {
	UClass* Cls = GetClass();
	/* Only register concrete subclasses, never the base itself */
	if (Cls == UK2Node_Tween::StaticClass()) { return; }
	if (Reg.IsOpenForRegistration(Cls))
		Reg.AddBlueprintAction(Cls, UBlueprintNodeSpawner::Create(Cls));
}

void UK2Node_Tween::PinDefaultValueChanged(UEdGraphPin* Pin) {
	Super::PinDefaultValueChanged(Pin);

	if (Pin->PinName == TEXT("Tween_Settings_Ease")) {
		EnsureHiddenState();

		if (UEdGraph* Graph = GetGraph()) {
			Graph->NotifyGraphChanged();
		}
	}
}

void UK2Node_Tween::EnsureSplitState() {
	const UEdGraphSchema_K2* Schema = GetDefault<UEdGraphSchema_K2>();

	// Level 1: FTweenFloatConfig  From, To, Settings
	if (UEdGraphPin* P = FindPin(TEXT("Tween")))
		if (P->SubPins.Num() == 0)
			Schema->SplitPin(P);

	// Level 2: FTweenSettings  Duration, Ease, RepeatCount, LoopMode, Delays
	if (UEdGraphPin* P = FindPin(TEXT("Tween_Settings")))
		if (P->SubPins.Num() == 0)
			Schema->SplitPin(P);

	// Level 3: FTweenDelays Start, Reverse, Repeat, End
	// Pre-splitting here means individual float pins are already visible
	// when \/ is opened, rather than a blob the user would need to split.
	if (UEdGraphPin* P = FindPin(TEXT("Tween_Settings_Delays")))
		if (P->SubPins.Num() == 0)
			Schema->SplitPin(P);

	CustomizedSplits();
}

void UK2Node_Tween::EnsureHiddenState() {
	UEdGraphPin* EasePin = FindPin(TEXT("Tween_Settings_Ease"));
	UEdGraphPin* CurvePin = FindPin(TEXT("Tween_Settings_CustomEaseCurve"));
	if (EasePin && CurvePin) {
		const UEnum* EaseEnum = StaticEnum<ETweenEase>();
		if (EaseEnum) {
			FString EaseValue = EasePin->DefaultValue.IsEmpty()
				? EasePin->AutogeneratedDefaultValue
				: EasePin->DefaultValue;
			int64 EnumValue = EaseEnum->GetValueByNameString(EaseValue);
			ETweenEase CurrentEase = static_cast<ETweenEase>(EnumValue);

			CurvePin->bHidden = (CurrentEase != ETweenEase::CustomCurve);
		}
	}
}

void UK2Node_Tween::EnsureAdvancedView() {
	/* Hide all Tween settings except Duration and Ease by default */
	for (UEdGraphPin* P : Pins) {
		const FString Name = P->PinName.ToString();

		if (!Name.StartsWith(TEXT("Tween_Settings"))) { continue; }
		if (Name == TEXT("Tween_Settings_Duration")) { continue; }
		if (Name == TEXT("Tween_Settings_Ease")) { continue; }
		if (Name == TEXT("Tween_Settings_CustomEaseCurve")) { continue; }

		P->bAdvancedView = true;
	}

	CustomizedAdvanced();
}
